<?php

/**
 * @file
 * Contains jamchart.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamchart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamchart module.
    case 'help.page.jamchart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chart of how often we jam') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jamchart_theme() {
  return [
    'jamchart' => [
      'render element' => 'children',
    ],
  ];
}
